### ISSUE TITLE
extract.Var n'extrait pas la variable

### ISSUE THREAD

**Issue by lou-heraut** [vmansanarez/AoTre#1]
Salut c'est Louis,
Dis moi si je me trompe mais extract.Var n'extrait pas la variable dans l'exemple ci-dessous et je me retrouve avec un tibble extrait de même taille que mon entrée. Est-ce que j'ai raté quelque chose dans ta maj ?

``` r
library(dplyr)
library(StatsAnalysisTrend)

Start = as.Date("1972-01-01")
End = as.Date("2020-12-31")
Date = seq.Date(Start, End, by="day")

Q = seq(1, length(Date)) + runif(length(Date), -100, 100)

df_list = list(
    data=tibble(Date=Date,
                group=1,
                Value=Q),
    
    info=tibble(group=1,
                code="A"))

df_Ex = extract.Var(data.station=df_list,
                    funct=min,
                    period=NULL,
                    per.start="01-01",
                    timestep='year',
                    pos.datetime=1,
                    na.rm=TRUE)

# df_trend = Estimate.stats(data.extract=df_Ex,
#                           level=0.1,
#                           dep.option='AR1')
```

**Comment by vmansanarez** [comment]
It should work now.

**Comment by lou-heraut** [comment]
Don't know why but it still don't work with my example above ... 
I use thoses commands for update : 
``` r
library(devtools)
install_github("https://github.com/vmansanarez/AoTre.git")
```

**Comment by vmansanarez** [comment]
Salut Louis,

Cela devrait marcher pourtant. J'ai nettoyé l'installation du package sur ma machine localement, redocumenté le tout et réinstallé le package via github.
Peux-tu ressayer? Si cela ne marche toujours pas, peux-tu faire les manipulations suivantes:

dans R, rentre laligne suivantedans la console:
> .libPaths()
Cela te donne le ou les chemins de ta ou tes librairies R. Dans celle-ci, cherche le dossier "StatsAnalysisTrend" et supprime le.
Relance R et refait:
> library(devtools)
> install_github("https://github.com/vmansanarez/AoTre.git")

**Comment by lou-heraut** [comment]
Parfait tout semble remarcher ! merci !!
