### ISSUE TITLE
NA management in extract.Var

### ISSUE THREAD

**Issue by lou-heraut** [vmansanarez/AoTre#2]
Salut Valentin,

Tout semble bien marcher mais j'ai un problème lors de l'extraction de mes variables qui doit venir d'une de tes nouvelles mise à jour qui concerne la présence de `NA` dans une série de données.
Dans mon exemple ci-dessous, j'effectue un échantillonnage des données où je sélectionne seulement les valeurs de débit de mai à novembre par exemple. Les autres valeurs dans l’année sont donc fixées à `NA` et il me semble par conséquent que `extract.Var` convertit l'année entière en `NA` dans ce cas là ... Est-ce que je pourrais avoir accès à un paramètre qui empêche cette nouvelle fonctionnalité où tu me conseil autre chose ? 

(je serais par contre intéressé de savoir où se trouve tes lignes de code qui permettent cette action étant donné son efficacité)

``` r
library(dplyr)
library(StatsAnalysisTrend)

# Date
Start = as.Date("1972-01-01")
End = as.Date("2020-12-31")
Date = seq.Date(Start, End, by="day")

# Flow value
Q = seq(1, length(Date)) + runif(length(Date), -100, 100)

# Sampling
Month = as.numeric(format(Date, "%m"))
SampleStart = 5
SampleEnd = 11
Q[Month < SampleStart | Month > 11] = NA

# List creation
df_list = list(
    data=tibble(Date=Date,
                group=1,
                Value=Q),
    
    info=tibble(group=1,
                code="A"))

# Extraction
df_Ex = extract.Var(data.station=df_list,
                    funct=min,
                    period=NULL,
                    per.start="01-01",
                    timestep='year',
                    pos.datetime=1,
                    na.rm=TRUE)
print(df_Ex)

# Estimation
df_trend = Estimate.stats(data.extract=df_Ex,
                          level=0.1,
                          dep.option='AR1')
print(df_trend)
```

**Comment by vmansanarez** [comment]
Résolu.
extract.Var ne prenait plus compte des arguments optionnels de la function 'funct'. Et donc les NA étaient pris en compte lors du calcul.

**Comment by lou-heraut** [comment]
Super merci, tout semble marcher ! mais par contre la mise à jour s'est appliqué que lorsque j'ai re effectué la marche à suivre que tu m'avais précédemment décrite : 
> .libPaths()
Cela te donne le ou les chemins de ta ou tes librairies R. Dans celle-ci, cherche le dossier "StatsAnalysisTrend" et supprime le.
Relance R et refait:
library(devtools)
install_github("https://github.com/vmansanarez/AoTre.git")

**Comment by lou-heraut** [comment]
Par contre avec le même exemple que je t'ai donné je ne comprend pas pourquoi je me retrouve avec deux lignes de résultats d'analyse de tendance à la fin de `Estimate.stats` ... Est-ce que c'est normal ?

**Comment by vmansanarez** [comment]
Fixed. Il prennait en compte la nouvelle column avec les pourcentage de NAs

**Comment by lou-heraut** [comment]
Super merci !
