### ISSUE TITLE
Échec de l'extraction lorsque funct renvoie Inf ou integer(0) pour une année sans donnée

### ISSUE THREAD

**Issue by lou-heraut** [vmansanarez/AoTre#4]
Salut, lorsqu'une année complète est `NA`, il arrive avec certaine fonction qui retourne `Inf` ou `integer(0)` que l'extraction plante. J'ai pu contourner le problème généré par le code ci-dessous en créant une fonction perso `which.minNA` qui remplace la valeur de `which.min` par un `NA` si elle c'est un `integer(0)` mais si tu as un moyen interne pour me passer de ça je suis preneur !

Merci d'avance

``` r
library(dplyr)
library(StatsAnalysisTrend)

# Date
Start = as.Date("1972-01-01")
End = as.Date("2020-12-31")
Date = seq.Date(Start, End, by="day")

# Flow value
Q = seq(1, length(Date)) + runif(length(Date), -100, 100)

# Sampling
Month = as.numeric(format(Date, "%m"))
SampleStart = 5
SampleEnd = 11
Q[Month < SampleStart | Month > 11] = NA
Q[format(Date, "%Y") == "1999"] = NA


# List creation
df_list = list(
    data=tibble(Date=Date,
                group=1,
                Value=Q),
    
    info=tibble(group=1,
                code="A"))


which.minShow = function (x) {
    print(x)
    print(which.min(x))
    print("")
    return (which.min(x))
}

which.minNA = function (x) {
    idMin = which.min(x)
    if (identical(idMin, integer(0))) {
        idMin = NA
    }
    return (idMin)
}

# Extraction
df_Ex = extract.Var(data.station=df_list,
                    funct=which.minShow,
                    # funct=which.minNA,
                    period=c(as.Date("1990-01-01"), as.Date("2000-12-31")),
                    per.start="01-01",
                    timestep='year',
                    pos.datetime=1)

# Estimation
df_trend = Estimate.stats(data.extract=df_Ex,
                          level=0.1,
                          dep.option='AR1')
```

**Comment by vmansanarez** [comment]
Salut Louis,
Lorsque la fonction retourne +/- Inf il n'y a pas de problèmes, un avertissement est issu mais "extract.Var" transforme automatiquement n'importequ'elle valeur Inf par NA. Exemple en utilisant "min" ou "max"

Pour "integer(0)", cela ne va pas être possible car le retour en lui même "integer(0)" pour une année n'est pas compatible en dimension avec les autres normales données. Donc la structure même tibble plante car les dimensions sont differentes entre "Date" et "value". Par exemple, c(1.0,2.0,integer(0),3.2) est de dimension 3 et non 4.

La seule facon de faire est de créer une fonction wrapper comme celle que tu as fait ("which.minNA") qui va contourner ce problème de dimension.
