### ISSUE TITLE
Citation du package

### ISSUE THREAD

**Issue by lou-heraut** [vmansanarez/AoTre#5]
Salut Valentin, 
Je rédige un petit rapport et je voulais citer ton package. Est ce que tu pourrais m'indiquer comment je pourrais le citer ? Tu pourrais rajouter un champ dans ton fichier DESCRIPTION pour avoir la ligne de commande `citation("StatsAnalysisTrend")` fonctionnelle !

**Comment by lou-heraut** [comment]
Du coup Michel m'avait donné les indications donc j'ai pu le faire ! 
Au cas où ...
```latex
@article{mansanarez2022,
  title={A R package for quickly updating trend analyses: application to French streamflow time series},
  author={Mansanarez, Valentin and Renard, Benjamin and Lang, Michel},
  journal={IAHS},
  year={2022},
  address={Montpellier, France},
}
```

**Comment by vmansanarez** [comment]
Ok thanks Louis
